image: Ubuntu
stack: jdk 11

branches:
  only:
    - master

build: off

install:
  - chmod +x gradlew
  - nohup java -jar ./artifacts/app-order.jar > server.log 2>&1 &
  - sleep 5

build_script:
  - ./gradlew test --info